# Generated by Django 5.2.4 on 2025-07-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_currect',
            new_name='is_correct',
        ),
    ]
